builders:
  drift_reference:
    import: "package:drift_custom/builders.dart"
    build_extensions: { ".dart": [ ".ref.dart",".ctr.dart" ] }
    builder_factories: [ "referenceBuilder","constructorBuilder" ]
    auto_apply: dependents
    build_to: source

